In [7]:
import pickle
import numpy as np

with open("matrices.pkl", "rb") as f:
    data = pickle.load(f)
    img_a = data["a"]
    img_b = data["b"]
    
img_a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [38]:
np.unique(img_a)

array([  0, 255], dtype=uint8)

In [39]:
np.unique(img_b)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  15,  16,  17,  33, 223, 236, 238, 239, 240, 241, 242, 243,
       244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255],
      dtype=uint8)

My guess is simple:\
JPEG format is lossy, which may introduce artifacts to the image.\
While PNG is lossless, meaning it does not lose information, and does not introduce artifacts to the image.

As we can clearly see, img_a has only 2 values (0, 255) while img_b has many more values.\
My guess is that those extra values are JPEG artifacts, therefore img_a is PNG, and img_b is JPEG